<?php
/**
 * @file
 * Code for the IPBG Views feature.
 */

include_once 'ipbg_views.features.inc';

/*
 * Implements hook_views_pre_render()
 */
function ipbg_views_views_pre_render(&$view) {
  if ($view->name == 'node_product_search_api' && $view->current_display == 'panel_pane_1') {
    $view->style_plugin->row_plugin->rendered_content[540]['#entity_view_mode']['view_mode'] = 'featured';
    $view->style_plugin->row_plugin->rendered_content[540]['#view_mode'] = 'featured';
  }

}